version: "3"
services:
  vue:
    image: node:18-alpine
    volumes:
      - ./frontend/src:/app
    working_dir: /app/vue-project
    command: >
      sh -c "npm update && npm install && npm run build"
  backend:
    image: backend:latest
    volumes:
      - ./backend-src:/home/src
    working_dir: /home/src 
    command: >
      bash -c "npm update &&
               npm install &&
               node server.js"
    networks:
      capstone:
        ipv4_address: "192.168.0.201"
    extra_hosts:
      - "wsuv-hp-capstone.com:192.168.0.101"
      - "api.wsuv-hp-capstone.com:192.168.0.201"
      - "db.wsuv-hp-capstone.com:192.168.0.202"
  database:
    image: mongo:8.0-noble
    volumes:
      - ./db:/data/db
    networks:
      capstone:
        ipv4_address: "192.168.0.202"
    ports: 
      - "27017:27017"
    extra_hosts:
      - "wsuv-hp-capstone.com:192.168.0.101"
      - "api.wsuv-hp-capstone.com:192.168.0.201"

  frontend:
    image: nginx
    volumes:
      - ./configs/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend-src:/var/www/html #serve the files in the vue app
    networks:
      capstone:
        ipv4_address: "192.168.0.101"
    extra_hosts:
      - "wsuv-hp-capstone.com:192.168.0.101"
      - "api.wsuv-hp-capstone.com:192.168.0.201"
      - "db.wsuv-hp-capstone.com:192.168.0.202"
    ports:
      - "80:80"
networks:
  capstone:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
