version: "3"
services:
  frontend:
    image: frontend:latest
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/src:/var/www/html
    ports:
      - "80:80"
    networks:
      capstone:
        ipv4_address: "192.168.0.101"
  backend:
    image: backend:latest
    volumes:
      - ./backend/src:/home/src
    working_dir: /home/src 
    command: >
      bash -c "npm update &&
               npm install &&
               node server.js"
    networks:
      capstone:
        ipv4_address: "192.168.0.201"
  database:
    image: mongo:8.0-noble
    ports: 
      - "27017:27017"
networks:
  capstone:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
