version: "3"
services:
  vue:
    image: node:18-alpine
    networks:
      capstone:
        ipv4_address: ${IP_FRONTEND}
    extra_hosts:
      - "wsuv-hp-capstone.com:${IP_FRONTEND}"
      - "api.wsuv-hp-capstone.com:${IP_BACKEND}"
      - "db.wsuv-hp-capstone.com:${IP_DB}"
    volumes:
      - ../frontend-src:/app
    working_dir: /app/vue-project
    command: >
      sh -c "npm update && npm install && npm run dev -- --port 80 --host"
    ports:
      - 80:80
  backend:
    image: backend:latest
    volumes:
      - ../backend-src:/home/src
    working_dir: /home/src 
    command: >
      bash -c "npm update &&
               npm install -g nodemon &&
               npm install &&
               nodemon server.js"
    networks:
      capstone:
        ipv4_address: "${IP_BACKEND}"
    extra_hosts:
      - "wsuv-hp-capstone.com:${IP_FRONTEND}"
      - "api.wsuv-hp-capstone.com:${IP_BACKEND}"
      - "db.wsuv-hp-capstone.com:${IP_DB}"
  database:
    image: mongo:8.0-noble
    volumes:
      - ../db:/data/db
    networks:
      capstone:
        ipv4_address: "${IP_DB}"
    extra_hosts:
      - "wsuv-hp-capstone.com:${IP_FRONTEND}"
      - "api.wsuv-hp-capstone.com:${IP_BACKEND}"
      - "db.wsuv-hp-capstone.com:${IP_DB}"
networks:
  capstone:
    ipam:
      driver: default
      config:
        - subnet: "${IP_SUBNET}"
#  frontend:
#    image: nginx
#    volumes:
#      - ./configs/default.conf:/etc/nginx/conf.d/default.conf
#      - ./frontend-src:/var/www/html
#    networks:
#      capstone:
#        ipv4_address: "192.168.97.101"
#    extra_hosts:
#      - "wsuv-hp-capstone.com:192.168.97.101"
#      - "api.wsuv-hp-capstone.com:192.168.97.201"
#      - "db.wsuv-hp-capstone.com:192.168.97.202"
#    ports:
#      - "80:80"
